//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonThu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDonThu()
        {
            this.CTHoaDonThus = new HashSet<CTHoaDonThu>();
        }
    
        public System.Guid IdPhieuThu { get; set; }
        public string MaHoaDonThu { get; set; }
        public Nullable<System.Guid> KhachHang { get; set; }
        public Nullable<System.DateTime> NgayThu { get; set; }
        public Nullable<int> TongSoLuong { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHoaDonThu> CTHoaDonThus { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
