//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonChi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDonChi()
        {
            this.CTHoaDonChis = new HashSet<CTHoaDonChi>();
        }
    
        public System.Guid IdPhieuChi { get; set; }
        public string MaHoaDonChi { get; set; }
        public Nullable<System.Guid> IdNhacungCap { get; set; }
        public Nullable<System.Guid> IdKhoXe { get; set; }
        public Nullable<System.DateTime> NgayChi { get; set; }
        public Nullable<int> TongSoLuong { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHoaDonChi> CTHoaDonChis { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
